[CmdletBinding()]
param(
    [Parameter()]
    [string]$SeqUrl,

    [Parameter()]
    [string]$SeqApiKey,

    [Parameter()]
    [string]$ImageTag,

    [Parameter()]
    [string]$ComposeFile = "compose.mcp.yaml",

    [Parameter()]
    [string]$ContainerName = "",

    [Parameter()]
    [switch]$Build
)

$ErrorActionPreference = "Stop"

function Require-Command([string]$Name) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $Name"
    }
}

Require-Command "docker"

function Import-DotEnvIfPresent([string]$Path) {
    if (-not (Test-Path $Path)) {
        return
    }

    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) {
            return
        }

        $parts = $line -split "=", 2
        if ($parts.Count -ne 2) {
            return
        }

        $key = $parts[0].Trim()
        $value = $parts[1].Trim()
        if (-not $key) {
            return
        }

        if ($key -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
            return
        }

        # Precedence: explicit args > existing env > .env
        if (-not [Environment]::GetEnvironmentVariable($key, "Process")) {
            [Environment]::SetEnvironmentVariable($key, $value, "Process")
        }
    }
}

function Ensure-DotEnvTemplate([string]$Path) {
    if (Test-Path $Path) {
        return
    }

    @"
# Generated by scripts/run-mcp-compose.ps1
# Replace values below, or pass -SeqUrl and -SeqApiKey when invoking this script.
MCP_GENERIC_DOTENV=true
SEQ_URL=
SEQ_API_KEY=
MCP_IMAGE_TAG=latest
"@ | Set-Content -Path $Path -Encoding utf8
}

if ($SeqUrl) {
    $env:SEQ_URL = $SeqUrl
}

if ($SeqApiKey) {
    $env:SEQ_API_KEY = $SeqApiKey
}

if ($ImageTag) {
    $env:MCP_IMAGE_TAG = $ImageTag
}

# Load .env only as fallback source.
$dotenvPath = $null
if (Test-Path $ComposeFile) {
    $composeFullPath = (Resolve-Path $ComposeFile).Path
    $composeDir = Split-Path $composeFullPath -Parent
    $dotenvPath = Join-Path $composeDir ".env"
}
elseif ($PSScriptRoot) {
    $dotenvPath = Join-Path $PSScriptRoot ".env"
}
else {
    # Fallback to current directory for backwards compatibility.
    $dotenvPath = ".env"
}

Ensure-DotEnvTemplate $dotenvPath
$usingGenericDotEnv = Select-String -Path $dotenvPath -Pattern '^\s*MCP_GENERIC_DOTENV\s*=\s*true\s*$' -Quiet

Import-DotEnvIfPresent $dotenvPath

if (-not $env:MCP_IMAGE_TAG) {
    $env:MCP_IMAGE_TAG = "latest"
}

if ($usingGenericDotEnv -and (-not $SeqUrl -or -not $SeqApiKey)) {
    throw "This run is using a generated generic .env template at '$dotenvPath'. Provide both -SeqUrl and -SeqApiKey."
}

if (-not $env:SEQ_URL) {
    throw "SEQ_URL is required. Provide -SeqUrl, set SEQ_URL, or add SEQ_URL to .env"
}

if (-not $env:SEQ_API_KEY) {
    throw "SEQ_API_KEY is required. Provide -SeqApiKey, set SEQ_API_KEY, or add SEQ_API_KEY to .env"
}

docker compose -f $ComposeFile images -q seq-otel-mcp *> $null
$imageId = $null
if ($LASTEXITCODE -eq 0) {
    $imageId = docker compose -f $ComposeFile images -q seq-otel-mcp
}
$imageExists = -not [string]::IsNullOrWhiteSpace($imageId)

if ($Build.IsPresent -or -not $imageExists) {
    docker compose -f $ComposeFile build seq-otel-mcp
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose build failed."
    }
}

Write-Host "Starting MCP server over stdio using docker compose..."
if ($ContainerName) {
    docker compose -f $ComposeFile run --rm -i --name $ContainerName seq-otel-mcp
}
else {
    docker compose -f $ComposeFile run --rm -i seq-otel-mcp
}
