#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-compose.mcp.yaml}"
SEQ_URL_ARG=""
SEQ_API_KEY_ARG=""
IMAGE_TAG_ARG=""
BUILD="false"
CONTAINER_NAME=""

usage() {
  cat <<EOF
Usage: scripts/run-mcp-compose.sh [options]

Options:
  --seq-url <url>           Seq URL (optional if SEQ_URL already set)
  --seq-api-key <key>       Seq API key (optional if SEQ_API_KEY already set)
  --image-tag <tag>         Image tag override (default: latest)
  --compose-file <path>     Compose file (default: compose.mcp.yaml)
  --container-name <name>   Container name override (default: Docker-generated random name)
  --build                   Build image before run
  -h, --help                Show help
EOF
}

require_option_value() {
  local option="$1"
  local value="${2-}"
  if [[ -z "$value" || "$value" == -* ]]; then
    echo "Missing value for $option option." >&2
    usage
    exit 1
  fi
}

ensure_dotenv_file() {
  local path="$1"
  if [[ -f "$path" ]]; then
    return
  fi

  cat > "$path" <<EOF
# Generated by scripts/run-mcp-compose.sh
# Replace values below, or provide SEQ_URL/SEQ_API_KEY via env or script args when invoking this script.
MCP_GENERIC_DOTENV=true
SEQ_URL=
SEQ_API_KEY=
MCP_IMAGE_TAG=latest
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --seq-url)
      require_option_value "$1" "${2-}"
      SEQ_URL_ARG="$2"
      shift 2
      ;;
    --seq-api-key)
      require_option_value "$1" "${2-}"
      SEQ_API_KEY_ARG="$2"
      shift 2
      ;;
    --image-tag)
      require_option_value "$1" "${2-}"
      IMAGE_TAG_ARG="$2"
      shift 2
      ;;
    --compose-file)
      require_option_value "$1" "${2-}"
      COMPOSE_FILE="$2"
      shift 2
      ;;
    --container-name)
      require_option_value "$1" "${2-}"
      CONTAINER_NAME="$2"
      shift 2
      ;;
    --build)
      BUILD="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -n "$SEQ_URL_ARG" ]]; then
  export SEQ_URL="$SEQ_URL_ARG"
fi

if [[ -n "$SEQ_API_KEY_ARG" ]]; then
  export SEQ_API_KEY="$SEQ_API_KEY_ARG"
fi

if [[ -n "$IMAGE_TAG_ARG" ]]; then
  export MCP_IMAGE_TAG="$IMAGE_TAG_ARG"
fi

if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "Compose file not found: $COMPOSE_FILE" >&2
  exit 1
fi

compose_dir="$(cd "$(dirname "$COMPOSE_FILE")" && pwd)"
DOTENV_PATH="$compose_dir/.env"

ensure_dotenv_file "$DOTENV_PATH"
USING_GENERIC_DOTENV="false"
if grep -Eq '^[[:space:]]*MCP_GENERIC_DOTENV[[:space:]]*=[[:space:]]*true[[:space:]]*$' "$DOTENV_PATH"; then
  USING_GENERIC_DOTENV="true"
fi

# Fallback to .env only for missing values.
if [[ -f "$DOTENV_PATH" ]]; then
  while IFS= read -r line; do
    [[ -z "${line// }" ]] && continue
    [[ "$line" == \#* ]] && continue
    if [[ "$line" == *=* ]]; then
      key="${line%%=*}"
      value="${line#*=}"
      key="${key//[[:space:]]/}"
      value="${value%$'\r'}"
      value="${value#"${value%%[![:space:]]*}"}"
      value="${value%"${value##*[![:space:]]}"}"
      if ! [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
        continue
      fi
      if [[ -n "$key" && -z "${!key:-}" ]]; then
        export "$key=$value"
      fi
    fi
  done < "$DOTENV_PATH"
fi

if [[ -z "${MCP_IMAGE_TAG:-}" ]]; then
  export MCP_IMAGE_TAG="latest"
fi

if [[ "$USING_GENERIC_DOTENV" == "true" ]]; then
  if [[ -z "${SEQ_URL:-}" || -z "${SEQ_API_KEY:-}" ]]; then
    echo "This run is using a generated generic .env template at '$DOTENV_PATH'." >&2
    echo "Ensure SEQ_URL and SEQ_API_KEY are set via environment variables, a populated .env, or script arguments." >&2
    usage
    exit 1
  fi
fi

if [[ -z "${SEQ_URL:-}" ]]; then
  echo "SEQ_URL is required. Use --seq-url, set SEQ_URL, or add SEQ_URL to .env." >&2
  exit 1
fi

if [[ -z "${SEQ_API_KEY:-}" ]]; then
  echo "SEQ_API_KEY is required. Use --seq-api-key, set SEQ_API_KEY, or add SEQ_API_KEY to .env." >&2
  exit 1
fi

if [[ "$BUILD" != "true" ]]; then
  IMAGE_ID="$(docker compose -f "$COMPOSE_FILE" images -q seq-otel-mcp 2>/dev/null || true)"
  if [[ -z "$IMAGE_ID" ]]; then
    BUILD="true"
  fi
fi

if [[ "$BUILD" == "true" ]]; then
  docker compose -f "$COMPOSE_FILE" build seq-otel-mcp
fi

echo "Starting MCP server over stdio using docker compose..."
if [[ -n "$CONTAINER_NAME" ]]; then
  exec docker compose -f "$COMPOSE_FILE" run --rm -i --name "$CONTAINER_NAME" seq-otel-mcp
else
  exec docker compose -f "$COMPOSE_FILE" run --rm -i seq-otel-mcp
fi
