[CmdletBinding()]
param(
    [Parameter()]
    [string]$SeqUrl,

    [Parameter()]
    [string]$SeqApiKey,

    [Parameter()]
    [string]$ImageTag,

    [Parameter()]
    [string]$ComposeFile = "compose.mcp.yaml",

    [Parameter()]
    [string]$ContainerName = "",

    [Parameter()]
    [switch]$Build
)

$ErrorActionPreference = "Stop"

function Require-Command([string]$Name) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $Name"
    }
}

Require-Command "docker"

function Import-DotEnvIfPresent([string]$Path) {
    if (-not (Test-Path $Path)) {
        return
    }

    foreach ($rawLine in Get-Content $Path) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith("#")) {
            continue
        }

        $parts = $line -split "=", 2
        if ($parts.Count -ne 2) {
            continue
        }

        $key = $parts[0].Trim()
        $value = $parts[1].Trim().TrimEnd("`r")
        if (-not $key) {
            continue
        }

        if ($key -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
            continue
        }

        # Precedence: explicit args > existing env > .env
        if (-not [Environment]::GetEnvironmentVariable($key, "Process")) {
            [Environment]::SetEnvironmentVariable($key, $value, "Process")
        }
    }
}

function Ensure-DotEnvTemplate([string]$Path) {
    if (Test-Path $Path) {
        return
    }

    @"
# Generated by scripts/run-mcp-compose.ps1
# Replace values below, or provide SEQ_URL/SEQ_API_KEY via env or script args when invoking this script.
MCP_GENERIC_DOTENV=true
SEQ_URL=
SEQ_API_KEY=
MCP_IMAGE_TAG=latest
"@ | Set-Content -Path $Path -Encoding utf8
}

if ($SeqUrl) {
    $env:SEQ_URL = $SeqUrl
}

if ($SeqApiKey) {
    $env:SEQ_API_KEY = $SeqApiKey
}

if ($ImageTag) {
    $env:MCP_IMAGE_TAG = $ImageTag
}

# Load .env only as fallback source.
if (-not (Test-Path -Path $ComposeFile -PathType Leaf)) {
    throw "Compose file not found: $ComposeFile"
}

$composeFullPath = (Resolve-Path $ComposeFile).Path
$composeDir = Split-Path $composeFullPath -Parent
$dotenvPath = Join-Path $composeDir ".env"

Ensure-DotEnvTemplate $dotenvPath
$usingGenericDotEnv = Select-String -Path $dotenvPath -Pattern '^\s*MCP_GENERIC_DOTENV\s*=\s*true\s*$' -Quiet

Import-DotEnvIfPresent $dotenvPath

if (-not $env:MCP_IMAGE_TAG) {
    $env:MCP_IMAGE_TAG = "latest"
}

if ($usingGenericDotEnv -and (-not $env:SEQ_URL -or -not $env:SEQ_API_KEY)) {
    throw "This run is using a generated generic .env template at '$dotenvPath'. Ensure SEQ_URL and SEQ_API_KEY are configured via environment variables, a populated .env, or script arguments."
}

if (-not $env:SEQ_URL) {
    throw "SEQ_URL is required. Provide -SeqUrl, set SEQ_URL, or add SEQ_URL to .env"
}

if (-not $env:SEQ_API_KEY) {
    throw "SEQ_API_KEY is required. Provide -SeqApiKey, set SEQ_API_KEY, or add SEQ_API_KEY to .env"
}

docker compose -f $ComposeFile images -q seq-otel-mcp *> $null
$imageId = $null
if ($LASTEXITCODE -eq 0) {
    $imageId = docker compose -f $ComposeFile images -q seq-otel-mcp
}
$imageExists = -not [string]::IsNullOrWhiteSpace($imageId)

if ($Build.IsPresent -or -not $imageExists) {
    docker compose -f $ComposeFile build seq-otel-mcp
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose build failed."
    }
}

Write-Host "Starting MCP server over stdio using docker compose..."
if ($ContainerName) {
    docker compose -f $ComposeFile run --rm -i --name $ContainerName seq-otel-mcp
}
else {
    docker compose -f $ComposeFile run --rm -i seq-otel-mcp
}
