export interface SeqRouteCatalogEntry {
  path: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  permission: string;
  additional: string;
  notes: string;
}

export const SEQ_ROUTE_CATALOG: SeqRouteCatalogEntry[] = [
  { path: "api", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/alerts", method: "GET", permission: "Read", additional: "Users can only read shared alerts, and those that they own.", notes: "" },
  { path: "api/alerts", method: "POST", permission: "Write", additional: "Users can only create shared alerts or personally owned ones. The additional Project permission is required to create protected alerts.", notes: "" },
  { path: "api/alerts/{id}", method: "DELETE", permission: "Write", additional: "Users can only remove shared alerts and those that they own. The additional Project permission is required to remove protected alerts.", notes: "" },
  { path: "api/alerts/{id}", method: "GET", permission: "Read", additional: "Users can only read shared alerts, and those that they own.", notes: "" },
  { path: "api/alerts/{id}", method: "PUT", permission: "Write", additional: "Users can only update shared alerts and those that they own. The additional Project permission is required to update protected alerts.", notes: "" },
  { path: "api/alerts/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/alerts/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "api/alertstate", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/alertstate/{id}", method: "DELETE", permission: "Project", additional: "", notes: "" },
  { path: "api/alertstate/{id}", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/alertstate/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/apikeys", method: "GET", permission: "Read", additional: "Only Project principals can view all keys; others can only request and view keys that they own.", notes: "" },
  { path: "api/apikeys", method: "POST", permission: "Write", additional: "A principal can only set the owner of a key to themselves. Only Project principals can create keys without an owner. Principals can only delegate permissions to a key that they themselves hold.", notes: "" },
  { path: "api/apikeys/{id}", method: "DELETE", permission: "Write", additional: "Only Project principals can remove any key; others can only remove keys that they own.", notes: "" },
  { path: "api/apikeys/{id}", method: "GET", permission: "Read", additional: "Only Project principals can view all keys; others can only request and view keys that they own.", notes: "" },
  { path: "api/apikeys/{id}", method: "PUT", permission: "Write", additional: "A principal can only set the owner of a key to themselves. Only Project principals can create keys without an owner. Principals can only delegate permissions to a key that they themselves hold.", notes: "" },
  { path: "api/apikeys/{id}/metrics/{measurement}", method: "GET", permission: "Read", additional: "Only Project principals can view metrics for all keys; others can only request and view metrics for keys that they own.", notes: "" },
  { path: "api/apikeys/metrics/{measurement}", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/apikeys/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/apikeys/template", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/appinstances", method: "GET", permission: "Read", additional: "Principals without Project permissions can only access basic details of available app instances.", notes: "" },
  { path: "api/appinstances", method: "POST", permission: "System", additional: "", notes: "" },
  { path: "api/appinstances/{id}", method: "DELETE", permission: "System", additional: "", notes: "" },
  { path: "api/appinstances/{id}", method: "GET", permission: "Read", additional: "Principals without Project permissions can only access basic details of available app instances.", notes: "" },
  { path: "api/appinstances/{id}", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/appinstances/{id}/icon", method: "GET", permission: "Read", additional: "Principals without Project permissions can only access basic details of available app instances.", notes: "" },
  { path: "api/appinstances/{id}/invoke", method: "POST", permission: "Write", additional: "The app instance id must be an output, and either accept direct invocation, or the principal must have System permissions.", notes: "" },
  { path: "api/appinstances/{id}/metrics/{measurement}", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/appinstances/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/appinstances/template", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/apps", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/apps/{id}", method: "DELETE", permission: "System", additional: "", notes: "" },
  { path: "api/apps/{id}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/apps/{id}/icon", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/apps/{id}/update", method: "POST", permission: "System", additional: "", notes: "" },
  { path: "api/apps/install", method: "POST", permission: "System", additional: "", notes: "" },
  { path: "api/apps/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/apps/template", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/backups", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/backups/{id}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/backups/files/{filename}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/backups/immediate", method: "POST", permission: "System", additional: "", notes: "Allows Cross-Site POSTs" },
  { path: "api/backups/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/cluster", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/cluster/{id}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/cluster/{id}/drain", method: "POST", permission: "System", additional: "", notes: "" },
  { path: "api/cluster/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/dashboards", method: "GET", permission: "Read", additional: "Users can only read shared dashboards, and those that they own.", notes: "" },
  { path: "api/dashboards", method: "POST", permission: "Write", additional: "Users can only create shared dashboards or personally owned ones. The additional Project permission is required to create protected dashboards.", notes: "" },
  { path: "api/dashboards/{id}", method: "DELETE", permission: "Write", additional: "Users can only remove shared dashboards and those that they own. The additional Project permission is required to remove protected dashboards.", notes: "" },
  { path: "api/dashboards/{id}", method: "GET", permission: "Read", additional: "Users can only read shared dashboards, and those that they own.", notes: "" },
  { path: "api/dashboards/{id}", method: "PUT", permission: "Write", additional: "Users can only update shared dashboards and those that they own. The additional Project permission is required to update protected dashboards.", notes: "" },
  { path: "api/dashboards/query/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "api/dashboards/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/dashboards/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "api/data", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/data", method: "POST", permission: "Read", additional: "", notes: "" },
  { path: "api/data/{signalId}", method: "GET", permission: "Read", additional: "", notes: "Obsolete" },
  { path: "api/data/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/deferred/{deferredId}", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/diagnostics/cluster/metrics", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/diagnostics/ingestion", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/diagnostics/metrics", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/diagnostics/metrics/{measurement}", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/diagnostics/report", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/diagnostics/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/diagnostics/status", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/diagnostics/storage", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/diagnostics/usage-telemetry", method: "POST", permission: "Read", additional: "", notes: "" },
  { path: "api/events", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/events/{id}", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/events/raw", method: "POST", permission: "Public", additional: "If the RequireApiKeyForWritingEvents setting is enabled, requests must be authenticated and have the Ingest permission.", notes: "Allows Cross-Site POSTs" },
  { path: "api/events/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/events/scan", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/events/scan", method: "POST", permission: "Read", additional: "", notes: "" },
  { path: "api/events/signal", method: "DELETE", permission: "Project", additional: "", notes: "" },
  { path: "api/events/signal", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/events/signal", method: "POST", permission: "Read", additional: "", notes: "" },
  { path: "api/events/signal/{signalId}", method: "GET", permission: "Read", additional: "", notes: "Obsolete" },
  { path: "api/events/stream", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/events/tabulate", method: "POST", permission: "Read", additional: "", notes: "" },
  { path: "api/events/tabulate/{signalId}", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/expressionindexes", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/expressionindexes", method: "POST", permission: "Write", additional: "", notes: "" },
  { path: "api/expressionindexes/{id}", method: "DELETE", permission: "Write", additional: "", notes: "" },
  { path: "api/expressionindexes/{id}", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/expressionindexes/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/expressionindexes/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "api/expressions/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/expressions/sql", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/expressions/strict", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/feeds", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/feeds", method: "POST", permission: "System", additional: "", notes: "" },
  { path: "api/feeds/{id}", method: "DELETE", permission: "System", additional: "", notes: "" },
  { path: "api/feeds/{id}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/feeds/{id}", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/feeds/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/feeds/template", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/indexes", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/indexes/{id}", method: "DELETE", permission: "Project", additional: "", notes: "" },
  { path: "api/indexes/{id}", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/indexes/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/integrationtest/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/licenses", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/licenses/{id}", method: "GET", permission: "Read", additional: "Read principals can see license status but System is required for certificate details.", notes: "" },
  { path: "api/licenses/{id}", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/licenses/downgrade", method: "POST", permission: "System", additional: "", notes: "" },
  { path: "api/licenses/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/permalinks", method: "GET", permission: "Read", additional: "Non-Project principals can only view their own permalinks.", notes: "" },
  { path: "api/permalinks", method: "POST", permission: "Write", additional: "Non-Project principals can only create permalinks for themselves.", notes: "" },
  { path: "api/permalinks/{id}", method: "DELETE", permission: "Write", additional: "Non-Project principals can only remove their own permalinks.", notes: "" },
  { path: "api/permalinks/{id}", method: "GET", permission: "Read", additional: "Non-Project principals can only retrieve their own permalinks.", notes: "" },
  { path: "api/permalinks/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/permalinks/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "api/retentionpolicies", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/retentionpolicies", method: "POST", permission: "Project", additional: "", notes: "" },
  { path: "api/retentionpolicies/{id}", method: "DELETE", permission: "Project", additional: "", notes: "" },
  { path: "api/retentionpolicies/{id}", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/retentionpolicies/{id}", method: "PUT", permission: "Project", additional: "", notes: "" },
  { path: "api/retentionpolicies/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/retentionpolicies/template", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/roles", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/roles/{id}", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/roles/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/runningtasks", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/runningtasks/{id}", method: "DELETE", permission: "System", additional: "", notes: "" },
  { path: "api/runningtasks/{id}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/runningtasks/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/settings/{id}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/settings/{id}", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/settings/internal-error-reporting", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/settings/internal-error-reporting", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/settings/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/settings/setting-authenticationprovider", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/settings/setting-checkforupdates", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-checkforupdates", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-instancetitle", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/settings/setting-isactivedirectoryauthentication", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/settings/setting-isauthenticationenabled", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/settings/setting-isusagetelemetryenabled", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/settings/setting-minimumfreestoragespace", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-minimumfreestoragespace", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-newusershowdashboardids", method: "GET", permission: "Organization", additional: "", notes: "" },
  { path: "api/settings/setting-newusershowdashboardids", method: "PUT", permission: "Organization", additional: "", notes: "" },
  { path: "api/settings/setting-newusershowqueryids", method: "GET", permission: "Organization", additional: "", notes: "" },
  { path: "api/settings/setting-newusershowqueryids", method: "PUT", permission: "Organization", additional: "", notes: "" },
  { path: "api/settings/setting-newusershowsignalids", method: "GET", permission: "Organization", additional: "", notes: "" },
  { path: "api/settings/setting-newusershowsignalids", method: "PUT", permission: "Organization", additional: "", notes: "" },
  { path: "api/settings/setting-raweventmaximumcontentlength", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-raweventmaximumcontentlength", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-rawpayloadmaximumcontentlength", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-rawpayloadmaximumcontentlength", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-requireapikeyforwritingevents", method: "GET", permission: "Project", additional: "", notes: "" },
  { path: "api/settings/setting-requireapikeyforwritingevents", method: "PUT", permission: "Project", additional: "", notes: "" },
  { path: "api/settings/setting-searchdurationseconds", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/settings/setting-searchdurationseconds", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-servicenameexpression", method: "GET", permission: "Read", additional: "", notes: "" },
  { path: "api/settings/setting-servicenameexpression", method: "PUT", permission: "Project", additional: "", notes: "" },
  { path: "api/settings/setting-themestyles", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/settings/setting-themestyles", method: "PUT", permission: "System", additional: "", notes: "" },
  { path: "api/signals", method: "GET", permission: "Read", additional: "Users can only read shared signals, and those that they own.", notes: "" },
  { path: "api/signals", method: "POST", permission: "Write", additional: "Users can only create shared signals or personally owned ones. The additional Project permission is required to create protected signals.", notes: "" },
  { path: "api/signals/{id}", method: "DELETE", permission: "Write", additional: "Users can only remove shared signals and those that they own. The additional Project permission is required to remove protected signals.", notes: "" },
  { path: "api/signals/{id}", method: "GET", permission: "Read", additional: "Users can only read shared signals, and those that they own.", notes: "" },
  { path: "api/signals/{id}", method: "PUT", permission: "Write", additional: "Users can only update shared signals and those that they own. The additional Project permission is required to update protected signals.", notes: "" },
  { path: "api/signals/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/signals/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "api/sqlqueries", method: "GET", permission: "Read", additional: "Users can only read shared SQL queries, and those that they own.", notes: "" },
  { path: "api/sqlqueries", method: "POST", permission: "Write", additional: "Users can only create shared SQL queries or personally owned ones. The additional Project permission is required to create protected SQL queries.", notes: "" },
  { path: "api/sqlqueries/{id}", method: "DELETE", permission: "Write", additional: "Users can only remove shared SQL queries and those that they own. The additional Project permission is required to remove protected SQL queries.", notes: "" },
  { path: "api/sqlqueries/{id}", method: "GET", permission: "Read", additional: "Users can only read shared SQL queries, and those that they own.", notes: "" },
  { path: "api/sqlqueries/{id}", method: "PUT", permission: "Write", additional: "Users can only update shared SQL queries and those that they own. The additional Project permission is required to update protected SQL queries.", notes: "" },
  { path: "api/sqlqueries/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/sqlqueries/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "api/updates", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/updates/{id}", method: "GET", permission: "System", additional: "", notes: "" },
  { path: "api/updates/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/users", method: "GET", permission: "Project", additional: "Only System principals can access authentication provider information for a user.", notes: "" },
  { path: "api/users", method: "POST", permission: "Organization", additional: "No principal can create a user with permissions that it does not itself have.", notes: "" },
  { path: "api/users/{id}", method: "DELETE", permission: "Organization", additional: "", notes: "" },
  { path: "api/users/{id}", method: "GET", permission: "Public", additional: "Users can retrieve their own records. Only Project principals can retrieve other principals. Only System principals can access authentication provider information for a user.", notes: "" },
  { path: "api/users/{id}", method: "PUT", permission: "Public", additional: "Users can update limited fields on their own records. Only Organization principals can update other principals. No principal can modify a user without holding all permissions held by the target user, and no principal can grant a user permissions that it does not itself have.", notes: "" },
  { path: "api/users/{id}/searches", method: "DELETE", permission: "Write", additional: "Only the principal's own search history can be cleared.", notes: "" },
  { path: "api/users/{id}/searches", method: "GET", permission: "Read", additional: "Only the principal's own search history can be retrieved.", notes: "" },
  { path: "api/users/{id}/searches/update", method: "POST", permission: "Write", additional: "Only the principal's own search history can be updated.", notes: "" },
  { path: "api/users/{id}/unlinkauthenticationprovider", method: "POST", permission: "System", additional: "", notes: "" },
  { path: "api/users/current", method: "GET", permission: "Public", additional: "Can only return logged-in user information.", notes: "" },
  { path: "api/users/login", method: "POST", permission: "Public", additional: "", notes: "" },
  { path: "api/users/logout", method: "POST", permission: "Public", additional: "", notes: "Allows Cross-Site POSTs" },
  { path: "api/users/providers", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/users/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/users/template", method: "GET", permission: "Organization", additional: "", notes: "" },
  { path: "api/workspaces", method: "GET", permission: "Read", additional: "Users can only read shared workspaces, and those that they own.", notes: "" },
  { path: "api/workspaces", method: "POST", permission: "Write", additional: "Users can only create shared workspaces or personally owned ones. The additional Project permission is required to create protected workspaces.", notes: "" },
  { path: "api/workspaces/{id}", method: "DELETE", permission: "Write", additional: "Users can only remove shared workspaces and those that they own. The additional Project permission is required to remove protected workspaces.", notes: "" },
  { path: "api/workspaces/{id}", method: "GET", permission: "Read", additional: "Users can only read shared workspaces, and those that they own.", notes: "" },
  { path: "api/workspaces/{id}", method: "PUT", permission: "Write", additional: "Users can only update shared workspaces and those that they own. The additional Project permission is required to update protected workspaces.", notes: "" },
  { path: "api/workspaces/resources", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "api/workspaces/template", method: "GET", permission: "Write", additional: "", notes: "" },
  { path: "health", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "health/cluster", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "ingest/clef", method: "POST", permission: "Public", additional: "If the RequireApiKeyForWritingEvents setting is enabled, requests must be authenticated and have the Ingest permission.", notes: "Allows Cross-Site POSTs" },
  { path: "ingest/otlp/v1/logs", method: "POST", permission: "Public", additional: "If the RequireApiKeyForWritingEvents setting is enabled, requests must be authenticated and have the Ingest permission.", notes: "Allows Cross-Site POSTs" },
  { path: "ingest/otlp/v1/metrics", method: "POST", permission: "Public", additional: "If the RequireApiKeyForWritingEvents setting is enabled, requests must be authenticated and have the Ingest permission.", notes: "Allows Cross-Site POSTs" },
  { path: "ingest/otlp/v1/traces", method: "POST", permission: "Public", additional: "If the RequireApiKeyForWritingEvents setting is enabled, requests must be authenticated and have the Ingest permission.", notes: "Allows Cross-Site POSTs" },
  { path: "integrated", method: "GET", permission: "Public", additional: "The Windows identity must already be authenticated.", notes: "" },
  { path: "oidc/challenge", method: "GET", permission: "Public", additional: "", notes: "" },
  { path: "oidc/challenge", method: "POST", permission: "Public", additional: "", notes: "" },
  { path: "theme/styles.css", method: "GET", permission: "Public", additional: "", notes: "" },
];

